// Generated by CoffeeScript 1.7.1

/*
	lessons-in-ember

	main.coffee

	@author Sean

	@note Created on 2014-11-16 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  jQuery(document).ready(function() {
    var checkSupport, checkToggleControls, main;
    checkSupport = function() {
      if ((typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.csstransforms : void 0) === false) {
        alert("Your browser does not appear to support CSS3 transforms.  Please note that the browser experience will likely suck or really lack stuff.  Maybe time to upgrade your browser (Chrome, Firefox, Opera)?");
      }
      if ((typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.cssanimations : void 0) === false) {
        alert("Your browser does not appear to support CSS3 animations.  This really is bad, and it means your experience is limited.  Maybe upgrade to Chrome, Firefox, or Opera?");
      }
      if ((typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.csstransforms3d : void 0) === false) {
        alert("Your browser does not appear to support CSS3 3d Transforms.  This is not so bad, but you should probably consider upgrading to a browser that has this (Chrome, Firefox, Opera.");
      }
      return (typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.csstransforms : void 0) && (typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.cssanimations : void 0) && (typeof Modernizr !== "undefined" && Modernizr !== null ? Modernizr.csstransforms3d : void 0);
    };
    checkToggleControls = function($slideArea, $toggledControls) {
      if ($slideArea.length < 1 || $toggledControls.length < 1) {
        console.warn("Could not find area for slides");
      }
      return $slideArea.on("enterStep", function() {
        if ($(this).hasClass("toggle-controls")) {
          return $toggledControls.toggle("fast");
        }
      });
    };
    main = function() {
      var $navControls, $nextButtons, $previousButtons, $slides;
      if (checkSupport()) {
        $navControls = $(".controls");
        $slides = $(".slides").jmpress();
        $nextButtons = $(".next-slide").on("click", function() {
          $(".slides").jmpress("next");
          return false;
        });
        return $previousButtons = $(".previous-slide").on("click", function() {
          $(".slides").jmpress("prev");
          return false;
        });
      }
    };
    return main();
  });

}).call(this);

//# sourceMappingURL=main.map
